json.name skill.name
json.id skill.id
json.description skill.description
json.start skill.start
json.end skill.end
json.user_id skill.user_id
json.projects skill.projects
json.resources skill.resources
json.user skill.user.name
